services: 
    postgres: 
        container_name: postgres-tralvel
        image: postgres:latest
        ports: 
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - docker.env
        networks:
            - postgres_network
    pgadmin: 
        links:
            - postgres:postgres 
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
            - "8080:80"
        volumes:
            - /data/pgadmin:/root/.pgadmin
        env_file:
            - docker.env
        networks:
            - postgres_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
    postgres_network:
        driver: bridge